---
title: "Lee Gianetti's Homework 4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    
    
---

 

```{r setup, include=FALSE}
library(flexdashboard) # always
```

## Column {.tabset .tabset-fade}

### Arrest Type Distribution

```{r}
## for del1Draft.rds
link1="https://github.com/dataviz690/hw-4/raw/main/plot1.rds"
readRDS(url(link1))
```

### Age Distribution across Arrest Type

```{r}
## for del2Draft.rds
link2="https://github.com/dataviz690/hw-4/raw/main/plot2.rds"
readRDS(url(link2))
```

### 2020 COVID-19 in South America

```{r}
## for del3Draft.rds
link3="https://github.com/dataviz690/hw-4/raw/main/plot3.rds"
readRDS(url(link3))
```

### Urban Safety


```{r fig.width=18, fig.height=10, out.width='100%'}
#link4="https://github.com/dataviz690/hw-4/raw/main/plot4.rds"
#readRDS(url(link4))

#link5="https://github.com/dataviz690/hw-4/raw/main/plot5.rds"
#readRDS(url(link5))
link6="https://github.com/dataviz690/hw-4/raw/main/plot45.rds"
readRDS(url(link6))
```