---
title: "hw-4 code"
output: html_notebook
---

First i will load library and clean memory

```{r}
#Load Libraries
rm(list = ls()) # clean memory
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggrepel)


```

I will now load my data

```{r}
#Load Data


file_path <- "C:/Users/lgianetti/OneDrive - City of Cambridge/DACSS Program/690V_data_viz/hw-4/Mass_Arrests.xlsx"

my_data <- read_excel(path = file_path,
    sheet = 1, col_names = TRUE, col_types = NULL, na = "", skip = 0)

```

I will do a quick look at the data

```{r}
#Look at Data
str(my_data, width = 70,strict.width='cut')
```

Now I will clean the data by correcting the data types and checking for missing values and outliers. I will also convert the appropriate columns to factors and numeric types as needed.

```{r}
#Clean Data
my_data$`Arrest Location` <- factor(my_data$`Arrest Location`)
my_data$`Arrest Offense by UCR Code` <- factor(my_data$`Arrest Offense by UCR Code`)
my_data$`Arrest Type` <- factor(my_data$`Arrest Type`)
my_data$`Sex` <- factor(my_data$`Sex`)
my_data$`Race` <- factor(my_data$`Race`)
my_data$`Ethnicity` <- factor(my_data$`Ethnicity`)
my_data$`Agency` <- factor(my_data$`Agency`)
my_data$`Incident Number` <- factor(my_data$`Incident Number`)



str(my_data, width = 70,strict.width='cut')
summary(my_data) # check for missing values and outliers



```
```{r}
# contingency table of counts
# independent variable in the columns - sex
# dependent variable in the rows - Arrest Type
(ArrestSex=table(my_data$'Arrest Type',my_data$Sex))

#choosing to exclude the 44 NA values in the table
```
```{r}
#marginal percentage (per column) from contingency table

ArrestSex.prop = prop.table(ArrestSex,2) |> 
  round(3)

ArrestSex.prop
```
```{r}
#making a data frame from the contingency table
ArrestSexDF=as.data.frame(ArrestSex)
names(ArrestSexDF)=c("Arrest Type","Sex","counts")

#adding marginal shares as percentages:
ArrestSexDF$pctCol=100*as.data.frame(ArrestSex.prop)[,3]

ArrestSexDF
```

```{r}
ggplot(data=ArrestSexDF, 
             aes(x=`Arrest Type`, y=counts)) + geom_bar(stat="identity")

```

```{r}
base1=ggplot(data=ArrestSexDF,
             aes(x=`Arrest Type`, y=counts,
                 fill=Sex)) 
barDodge1= base1 +  geom_bar(stat="identity",
                            position ='dodge') 
barDodge1 
```

```{r}
#cleaning up the order the arrest type shows in the plot
ArrestSexDF$`Arrest Type` <- factor(
  ArrestSexDF$`Arrest Type`,
  levels = c("M", "W", "F", "O")
)
base1_pct=ggplot(data=ArrestSexDF,
             aes(x=`Arrest Type`, y=pctCol,
                 fill=reorder(Sex,pctCol))) # reordering
barDodge1_pct= base1_pct +  geom_bar(stat="identity",
                            position ='dodge')+
  scale_x_discrete(labels = c(
    "M" = "Misdemeanor",
    "F" = "Felony",
    "W" = "Warrant",
    "O" = "Other"
  )) +
  scale_fill_manual(
    values = c(
      "F" = "#0072B2",   # Blue
      "M" = "#E69F00",   # Orange
      "U" = "#009E73"    # Green
    ),
  labels = c(
    "F" = "Female",
    "M" = "Male",
    "U" = "Unknown Gender"
  ))
                            
common_text_size <- 10

barDodge1_pct + labs(title = "Across All Genders, the Distribution of Arrests is Dominated by Misdemeanors",
                 subtitle = "Arrests by type from January 1, 2019 to March 28, 2020",
                 x="",
                 y="Share of all arrests (%)",
                 fill="",
                 caption = "Source: Mass-Arrests.xlsx\n44 cases of unknown arrest type excluded from plot") +  
            theme_classic() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.title = element_text(
      face = "bold",      
      size = 16
  )
    ) +
  theme(
    # Axis labels
    axis.title.x = element_text(size = common_text_size),
    axis.title.y = element_text(size = common_text_size),
    
    # Tick labels
    axis.text.x = element_text(size = common_text_size),
    axis.text.y = element_text(size = common_text_size),
    
    # Legend text
    legend.text = element_text(size = common_text_size),
    legend.title = element_text(size = common_text_size)
  ) + 
  geom_hline(yintercept = c(20, 40, 60), 
             linetype = "dashed", 
             color = "gray70")

#add 44 cases of unkow type exluded from the plot as a note in the caption

                    
```
```{r}
saveRDS(barDodge1_pct, file = "plot1.rds")
```

```{r}
#box plot to understand age distribution by arrest type without NA

my_data_no_na <- my_data |>
  filter(!is.na(`Arrest Type`))

overall_median <- median(my_data_no_na$Age, na.rm = TRUE)

order_levels <- my_data_no_na %>%
  group_by(`Arrest Type`) %>%
  summarize(median_age = median(Age, na.rm = TRUE)) %>%
  arrange(median_age) %>%
  pull(`Arrest Type`)

my_data_no_na$`Arrest Type` <- factor(
  my_data_no_na$`Arrest Type`,
  levels = order_levels
)

boxplot_age = ggplot(my_data_no_na, aes(x = `Arrest Type`, y = Age)) +
  geom_boxplot() +
  scale_x_discrete(labels = c(
    "M" = "Misdemeanor",
    "F" = "Felony",
    "W" = "Warrant",
    "O" = "Other"
  )) +
  labs(title = "Age Distribution by Arrest Type",
       x = "Arrest Type",
       y = "Age") +
  theme_classic() +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    axis.title.x = element_text(size = common_text_size),
    axis.title.y = element_text(size = common_text_size),
    axis.text.x = element_text(size = common_text_size),
    axis.text.y = element_text(size = common_text_size)
  ) +
  geom_hline(yintercept = overall_median,
             linetype = "dashed",
             color = "red")
boxplot_age
```

```{r}
box_violin <- ggplot(my_data_no_na, aes(x = `Arrest Type`, y = Age)) +
  geom_hline(yintercept = c(20, 40, 60, 80),
             linetype = "dashed",
             color = "gray70") +
  geom_hline(yintercept = overall_median,
             linetype = "solid",
             color = "red") +
  geom_violin(fill = "#4FA3D1", alpha = 0.65) +
  geom_boxplot(width = 0.1, fill = "white", outlier.shape = NA) +
  geom_text(
  stat = "summary",
  fun = median,
  aes(label = round(..y.., 1)),
  vjust = -0.7,
  size = common_text_size / 3) +
  annotate("text",
           x = .585,
           y = overall_median + 1.5,
           label = paste("Median Arrest\nAge =", round(overall_median, 1)),
           color = "red",
           size = 3) +
  scale_x_discrete(labels = c(
    "M" = "Misdemeanor",
    "F" = "Felony",
    "W" = "Warrant",
    "O" = "Other"
  )) +
  labs(
    title = "Across All Arrest Types, Arrest Age Distributions Cluster in the 20s and 30s",
    subtitle = "Median ages are similar across offense types, with only modest variation",
    x = "",
    y = "Age at Time of Arrest",
    caption = "Source: Mass-Arrests.xlsx\n44 cases of unknown arrest type excluded from plot"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    axis.title.x = element_text(size = common_text_size),
    axis.title.y = element_text(size = common_text_size),
    axis.text.x = element_text(size = common_text_size),
    axis.text.y = element_text(size = common_text_size)
  )

box_violin


```

```{r}
saveRDS(box_violin, file = "plot2.rds")
```

```{r}


my_data_covid <- read_csv("C:/Users/lgianetti/OneDrive - City of Cambridge/DACSS Program/690V_data_viz/hw-4/covid-19.csv",
    col_names = TRUE, col_types = NULL, na = "", skip = 0)

str(my_data_covid, width = 70,strict.width='cut')

```
```{r}

#Clean Data
my_data_covid$`Entity` <- factor(my_data_covid$`Entity`)
my_data_covid$`date` <- as.Date(my_data_covid$`date`)


str(my_data_covid, width = 70,strict.width='cut')
summary(my_data_covid) # check for missing values and outliers
```
```{r}
#create list of south american countries
south_american_countries <- c(
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Guyana",
  "Paraguay",
  "Peru",
  "Suriname",
  "Uruguay",
  "Venezuela"
)

#filter data for south american countries and only for 2020 and remove na values
my_data_covid_sa <- my_data_covid |>
  filter(Entity %in% south_american_countries,
  year == "2020",
  !is.na(daily_cases_mean),
  !is.na(daily_deaths_mean)
  )
  

summary(my_data_covid_sa)

```

```{r}
#Aggregate the mean cases for each country to ahow Average daily case levels over the year
covid_sa_agg <- my_data_covid_sa |>
  group_by(Entity) |>
  summarize(mean_daily_cases = mean(daily_cases_mean, na.rm = TRUE),
            mean_daily_deaths = mean(daily_deaths_mean, na.rm = TRUE)) |>
  arrange(desc(mean_daily_cases))

#adding peru highlight based on findings
covid_sa_agg <- covid_sa_agg |>
  mutate(highlight = ifelse(Entity == "Peru", "Peru", "Other"))

covid_sa_agg

```

```{r}
#creat a scatterplot
base = ggplot(covid_sa_agg) 
vars= base +  aes(x=mean_daily_deaths,y=mean_daily_cases)
geoms=vars + geom_point(aes(color = highlight), size = 2.5)

geoms  

#apply log scale to both axes to better visualize the relationship between cases and deaths across countries with very different levels of cases and deaths

geoms_log = geoms +scale_x_log10(
    breaks = c(0.1, 0.3, 1, 3),
    labels = c("0.1", "0.3", "1", "3")) +
  scale_y_log10(
    breaks = c(10, 30, 100),
    labels = c("10", "30", "100")
  )

geoms_log
```
```{r}
cor.test(covid_sa_agg$mean_daily_deaths,covid_sa_agg$mean_daily_cases,method = "pearson")
```
```{r}
#add labels to the scatterplot
scat_text = geoms_log + 
  geom_text_repel(aes(label = Entity, color = highlight), size = 2.8)

scat_text +
    scale_color_manual(
    values = c("Peru" = "firebrick", "Other" = "black")
  ) +
  labs(
    title = "Average Daily COVID-19 Cases and Deaths Appear Positively Correlated amoung South Americaian Countries in 2020, ",
    subtitle = "Peru stands out with relatively high average daily deaths compared to its average daily case levels",
    x = "Average Daily Deaths (log scale)",
    y = "Average Daily Cases (log scale)",
    caption = "Source: covid-19.csv\nData filtered for 2020 and South American countries only"
  ) +  
  theme_classic() +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    axis.title.x = element_text(size = common_text_size),
    axis.title.y = element_text(size = common_text_size),
    axis.text.x = element_text(size = common_text_size),
    axis.text.y = element_text(size = common_text_size)
  )

```
```{r}
saveRDS(scat_text, file = "plot3.rds")
```

